#!/usr/bin/env python3
"""update-pit-crew.py — Regenerates PIT-CREW.md with contributor rankings.
Called by post-commit hook or manually: python3 scripts/update-pit-crew.py
"""

import subprocess, os, sys, datetime
from collections import defaultdict

os.chdir(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], text=True).strip())

def git(*args):
    return subprocess.check_output(["git"] + list(args), text=True, stderr=subprocess.DEVNULL).strip()

# Gather raw author data keyed by email
authors = defaultdict(lambda: {"names": set(), "commits": 0, "added": 0, "removed": 0, "files": set(), "first": "9999-99-99", "last": "0000-00-00"})

# Commits per identity
for line in git("shortlog", "-sne", "--all").splitlines():
    line = line.strip()
    count, rest = line.split("\t", 1)
    count = int(count)
    name = rest.split(" <")[0]
    email = rest.split("<")[1].rstrip(">") if "<" in rest else rest
    authors[email]["names"].add(name)
    authors[email]["commits"] += count

# Lines added/removed and files per email
for email, data in authors.items():
    numstat = git("log", "--all", f"--author={email}", "--pretty=tformat:", "--numstat")
    for line in numstat.splitlines():
        parts = line.split("\t")
        if len(parts) >= 3 and parts[0] != "-":
            data["added"] += int(parts[0] or 0)
            data["removed"] += int(parts[1] or 0)

    names_only = git("log", "--all", f"--author={email}", "--pretty=tformat:", "--name-only")
    for f in names_only.splitlines():
        if f.strip():
            data["files"].add(f.strip())

    dates_raw = git("log", "--all", f"--author={email}", "--format=%ai", "--reverse")
    dates = [d.split(" ")[0] for d in dates_raw.splitlines() if d.strip()]
    if dates:
        data["first"] = min(data["first"], dates[0])
        data["last"] = max(data["last"], dates[-1])

# Sort by lines added descending
sorted_emails = sorted(authors.keys(), key=lambda e: authors[e]["added"], reverse=True)

total_commits = int(git("rev-list", "--all", "--count"))
total_files = len([f for f in subprocess.check_output(["find", ".", "-not", "-path", "./.git/*", "-type", "f"], text=True).splitlines() if f.strip() and "PIT-CREW.md" not in f])
timestamp = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

titles = ["Architect", "Navigator", "Mechanic", "Spotter", "Crew Chief", "Tire Changer", "Fueler", "Flag Bearer", "Pace Car", "Marshal"]
medals = {1: "\U0001f947", 2: "\U0001f948", 3: "\U0001f949"}

total_added = sum(authors[e]["added"] for e in sorted_emails)

lines = []
lines.append("# Pit Crew\n")
lines.append("> The people building this machine. Auto-generated from git history.\n")
lines.append(f"**Last updated:** {timestamp} | **Total commits:** {total_commits} | **Files in repo:** {total_files}\n")
lines.append("---\n")
lines.append("## Leaderboard\n")
lines.append("| Rank | Name | Role | Commits | Lines Added | Lines Removed | Net | Files Touched | Active Since | Last Seen |")
lines.append("|------|------|------|--------:|------------:|--------------:|----:|--------------:|:-------------|:----------|")

for i, email in enumerate(sorted_emails):
    d = authors[email]
    rank = i + 1
    name = sorted(d["names"], key=len, reverse=True)[0]  # pick longest name variant
    role = titles[i] if i < len(titles) else "Crew"
    medal = medals.get(rank, str(rank))
    net = d["added"] - d["removed"]
    files_count = len(d["files"])
    lines.append(f"| {medal} | **{name}** | {role} | {d['commits']} | +{d['added']} | -{d['removed']} | {net:+d} | {files_count} | {d['first']} | {d['last']} |")

lines.append("")
lines.append("## Contribution Mix\n")

for email in sorted_emails:
    d = authors[email]
    name = sorted(d["names"], key=len, reverse=True)[0]
    pct = (d["added"] * 100 // total_added) if total_added > 0 else 0
    bar_len = max(1, pct // 2)
    bar = "\u2588" * bar_len
    lines.append(f"- **{name}** {bar} {pct}% ({d['added']:,} lines)")

lines.append("")
lines.append("---\n")
lines.append("*Auto-generated by `scripts/update-pit-crew.py` on post-commit. Do not edit manually.*\n")

with open("PIT-CREW.md", "w") as f:
    f.write("\n".join(lines))

print(f"✓ PIT-CREW.md updated ({timestamp})")
